### ISSUE TITLE
Build issue due to missing org.bouncycastle dependency

### ISSUE THREAD

**Issue by zinal** [ydb-platform/ydb-java-sdk#43]
In the develop branch, build fails on test execution due to org.bouncycastle classes missing:

```
Errors: 
  ManagedChannelFactoryTest.customSslFactory:138 » Certificate No provider succeeded to generate a self-signed certificate. See debug log for the root cause.

Tests run: 50, Failures: 0, Errors: 1, Skipped: 0

------------------------------------------------------------------------
Reactor Summary:

Java SDK for YDB 2.1.0-SNAPSHOT .................... SUCCESS [  0.996 s]
Java SDK Bill of Materials 2.1.0-SNAPSHOT .......... SUCCESS [  0.069 s]
Auth API module 1.0.0 .............................. SUCCESS [  1.427 s]
Core module of Java SDK for YDB 2.1.0-SNAPSHOT ..... FAILURE [  3.661 s]
Tests common module 2.1.0-SNAPSHOT ................. SKIPPED
JUnit 4 support module 2.1.0-SNAPSHOT .............. SKIPPED
Table client implementation 2.1.0-SNAPSHOT ......... SKIPPED
Scheme client implementation 2.1.0-SNAPSHOT ........ SKIPPED
JUnit 5 support module 2.1.0-SNAPSHOT .............. SKIPPED
------------------------------------------------------------------------
BUILD FAILURE
```

The stacktraces contain the following:

```
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at io.grpc.netty.shaded.io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:246)
	... 33 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 34 more
```

**Comment by zinal** [comment]
Addition: this happens on JDK 17, JDK 1.8 works perfectly.
